### ISSUE TITLE
Missing `iran` when generating files

### ISSUE THREAD

**Issue by JohJohan** [mdomke/schwifty#104]
When generating files i miss `iran` because its not in the swift.com iban registry. 

We use this package for our python packages but we also have php project which uses Symfony that also has a iban validator there `iran` ibans are valid see the ticket i created there https://github.com/symfony/symfony/issues/46919

Its probably hard to add this case but it would at least be nice to inform people its missing iban countrys if there not on swift.com iban registry let me know what you guys think.

**Comment by johanadivare** [comment]
@mdomke

**Comment by mdomke** [comment]
@JohJohan with release `2024.1.1` IBANs from aspirational countries like Iran are supported.

```pycon
>>> from schwifty import IBAN
>>> IBAN("IR71 0570 0299 7160 1460 6410 01")
<IBAN=IR710570029971601460641001>
```
