### ISSUE TITLE
TypeError: write() argument must be str, not IBAN

### ISSUE THREAD

**Issue by xatarox** [mdomke/schwifty#106]
Tried to save to a text file the generated IBAN, however when I try this, it exits the script with the following error : 

TypeError: write() argument must be str, not IBAN

How can I find a way to fix this ?

**Comment by mdomke** [comment]
Can you give a complete minimal example for your problem?

**Comment by xatarox** [comment]
Yessir !
`GENERATED_IBANS = []
rnd_choice_AT=random.choice(AT)
iban = IBAN.generate("AT", bank_code=rnd_choice_AT, account_code=str(random.randint(10000000000, 99999999999)))
GENERATED_IBANS.append(iban)
`
[...]
`f = open(f"file.txt", "a", encoding='utf-8')
for i in GENERATED_IBANS:
    f.write(i)
    f.write("\n")`

**Comment by mdomke** [comment]
Well, the error message is pretty explicit, isn't it? The `file.write`-method only allows an argument of type `str` so that you either can use `IBAN.compact` or `str(IBAN(...))`
```python
with open("/tmp/iban.txt") as fp:
    for iban in GENERATED_IBANS:
        fp.write(iban.compact)
        fp.write("\n")
```
