### ISSUE TITLE
InvalidCountryCode: Unknown country-code 'PY'

### ISSUE THREAD

**Issue by jakubczaplicki** [mdomke/schwifty#110]
`Paraguay` is not defined in the IBAN spec registry:
```
def _get_iban_spec(country_code: str) -> dict:
    try:
        spec = registry.get("iban")
        assert isinstance(spec, dict)
        return spec[country_code]
    except KeyError:
        raise exceptions.InvalidCountryCode(f"Unknown country-code '{country_code}'")
```

raises `InvalidCountryCode: Unknown country-code 'PY' `

**Comment by mdomke** [comment]
@jakubczaplicki Paraguay is [not even listed](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country) as aspirational country. Please feel free to reopen this issue if you can provide some source with the structure of IBANs from Paraguay.
