### ISSUE TITLE
Wrong bank code regexp for GB IBANs

### ISSUE THREAD

**Issue by 990px** [mdomke/schwifty#13]
```
iban = IBAN("GB32ESSE40486562136016")
print(iban.bank_code)
'ESSE'
```
but should be `404865`.

via https://en.wikipedia.org/wiki/International_Bank_Account_Number

```
GBkk bbbb ssss sscc cccc cc
b = BIC bank code
s = Bank and branch code (sort code)
c = Account number 
```

`BIC bank code` != `bank code`

**Comment by mdomke** [comment]
`schwifty` uses the official SWIFT specification that can be found [here](https://www.swift.com/standards/data-standards/iban). If you look at section 2.25 of the IBAN registry linked from the SWIFT site you can see that the bank identifier is specified to be from position 1-4 of the BBAN and the branch identifier from 5-10.

```
BBAN = ESSE 404865 62136016
       ^  ^ ^    ^
       1  4 5    10
```

You have to acknowledge that `schwifty` uses a more generalized terminology for naming the different parts of an IBAN. The library doesn't know about any country specific wording (like sort code) nor does it take into account what additional national format might be applied to the different segments. So I think that considering the official specification `schwifty`'s behavior is correct.
