### ISSUE TITLE
InvalidCountryCode: Unknown country-code 'MA'

### ISSUE THREAD

**Issue by almathis** [mdomke/schwifty#141]
`MOROCCO` is not defined in the IBAN spec registry:

```
def _get_iban_spec(country_code: str) -> dict:
    try:
        spec = registry.get("iban")
        assert isinstance(spec, dict)
        return spec[country_code]
    except KeyError:
        raise exceptions.InvalidCountryCode(f"Unknown country-code '{country_code}'")
```

raises `InvalidCountryCode: Unknown country-code 'MA' `

Thanks for your work 🙏

**Comment by mdomke** [comment]
Many of the "aspirational" SWIFT countries have been added in release `2024.1.1.post0`. Thanks for reporting.
