### ISSUE TITLE
Implement "Pydantic protocol"

### ISSUE THREAD

**Issue by Kludex** [mdomke/schwifty#147]
Hi there 👋 

I'm not sure if you are familiar with [Pydantic](https://docs.pydantic.dev/latest/), but it's a relatively popular package within the Python community to do data validation/parsing/coercion.

I'd like to know if it would be possible to implement the [`__get_pydantic_core_schema__`](https://docs.pydantic.dev/latest/usage/types/custom/#creating-custom-classes-using-__get_pydantic_core_schema__) on `schwifty`.

If helps on the decision, `pandas` accepted the request: https://github.com/pandas-dev/pandas/issues/53999. 🙏 

As an alternative, we were implementing this on `pydantic-extra-types`: https://github.com/pydantic/pydantic-extra-types/pull/65.

**Comment by mdomke** [comment]
@waveman68 `schwifty` is indeed a library to work with SWIFT compliant Internation Bank Account Numbers (IBAN) and Bank Identifier Codes (BIC).

**Comment by mdomke** [comment]
@Kludex I will add support for the pydatnic protocol guarded with the optional dependency `schwifty[pydantic]`

**Comment by Kludex** [comment]
Nice! Thanks.

**Comment by mdomke** [comment]
Implemented in `2023.10.0`
