### ISSUE TITLE
'importlib.abc.Traversable' is deprecated and slated for removal in Python 3.14

### ISSUE THREAD

**Issue by jose-reveni** [mdomke/schwifty#158]
Deprecated since version 3.12, will be removed in version 3.14: Use [importlib.resources.abc.TraversableResources](https://docs.python.org/3/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources) instead.

**Comment by mdomke** [comment]
Thanks for the heads-up. However, we have to consider compatibility with older versions (at least Python 3.8, which is still [supported until end of 2024](https://devguide.python.org/versions/)). Do you actually mean `importlib.resources.abc.Traversable`? Feel free to add a conditional import to `schwifty.registry` to be forward compatible with upcoming versions!

**Comment by Natim** [comment]
I deep dived into this, apparently what has been deprecated is not the Traversable type but the `ResourceReader` type. @jose-reveni can you confirm that we don't need to do anything more here?

**Comment by yezz123** [comment]
Hey @Natim @mdomke coming for same error i'm facing here https://github.com/pydantic/pydantic-extra-types/actions/runs/7455350706/job/20284285629?pr=65 is there a way to support `from importlib_resources.abc import Traversable ` this to run because it's throwing same error:

PR: https://github.com/pydantic/pydantic-extra-types/pull/65

```py
__________________ ERROR collecting tests/test_json_schema.py __________________
tests/test_json_schema.py:12: in <module>
    from pydantic_extra_types.iban import Iban
pydantic_extra_types/iban.py:14: in <module>
    import schwifty
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/schwifty/__init__.py:6: in <module>
    from schwifty.bic import BIC
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/schwifty/bic.py:14: in <module>
    from schwifty import registry
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/schwifty/registry.py:14: in <module>
    from importlib.abc import Traversable
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/abc.py:35: in __getattr__
    warnings._deprecated(f"{__name__}.{name}", remove=(3, 14))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/warnings.py:529: in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
E   DeprecationWarning: 'importlib.abc.Traversable' is deprecated and slated for removal in Python 3.14
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by mdomke** [comment]
@yezz123 Why exactly do your tests fail for a `DeprecationWarning` that informs about the removal of a type in a Python version that's not expected to surface before 2025? I can however try to find a backwards compatible solution that makes this warning go away.
