### ISSUE TITLE
AttributeError: 'str' object has no attribute '_validate_characters'

### ISSUE THREAD

**Issue by nabudaldah** [mdomke/schwifty#163]
Using `schwifty.__version__` @ `'2023.10.0'`

I want to validate the following IBAN using the IBAN.validate() method:

`IBAN.validate('NL46ABNA0843913118')`

But I get the following error:

`AttributeError: 'str' object has no attribute '_validate_characters'`

**Comment by mdomke** [comment]
I think there is a misunderstanding on how to use the API of this library. You should simply call
```python
IBAN('NL46ABNA0843913118')
```
which will do the validation when the `IBAN` object is being initialized. See also the [documentation](https://schwifty.readthedocs.io/en/latest/examples.html#validation).

`IBAN.validate()` is in instance method and is called without arguments (in fact there is a boolean parameter which is also described in the [docs](https://schwifty.readthedocs.io/en/latest/api.html#schwifty.IBAN.validate)).
