### ISSUE TITLE
Validating IBANs in African countries result in 'Unknown country-code' error

### ISSUE THREAD

**Issue by n49o7** [mdomke/schwifty#171]
IBANs with the following prefixes return an error: `['BF', 'BJ', 'CI', 'CM', 'MA', 'MG', 'ML', 'NE', 'RW']`

The corresponding Country objects in `pycountries` are:

    [Country(alpha_2='BJ', alpha_3='BEN', flag='🇧🇯', name='Benin', numeric='204', official_name='Republic of Benin'),
     Country(alpha_2='BF', alpha_3='BFA', flag='🇧🇫', name='Burkina Faso', numeric='854'),
     Country(alpha_2='CI', alpha_3='CIV', flag='🇨🇮', name="Côte d'Ivoire", numeric='384', official_name="Republic of Côte d'Ivoire"),
     Country(alpha_2='CM', alpha_3='CMR', flag='🇨🇲', name='Cameroon', numeric='120', official_name='Republic of Cameroon'),
     Country(alpha_2='MA', alpha_3='MAR', flag='🇲🇦', name='Morocco', numeric='504', official_name='Kingdom of Morocco'),
     Country(alpha_2='MG', alpha_3='MDG', flag='🇲🇬', name='Madagascar', numeric='450', official_name='Republic of Madagascar'),
     Country(alpha_2='ML', alpha_3='MLI', flag='🇲🇱', name='Mali', numeric='466', official_name='Republic of Mali'),
     Country(alpha_2='NE', alpha_3='NER', flag='🇳🇪', name='Niger', numeric='562', official_name='Republic of the Niger'),
     Country(alpha_2='RW', alpha_3='RWA', flag='🇷🇼', name='Rwanda', numeric='646', official_name='Rwandese Republic')]

Interestingly, the BICs located in these countries are valid.

**Comment by Natim** [comment]
Hello @n49o7, do you have IBAN examples we can use to test the issue?

**Comment by Natim** [comment]
Hello @n49o7 I couldn't find countries listed above in this list: https://www.xe.com/ibancalculator/countrylist/

**Comment by mdomke** [comment]
In release `2024.1.1.post0` I added all countries that are listed on Wikipedia so that general support for these African countries should be available. The information about the BBAN structure is however very scarce, so that detail information (e.g. account number, bank code), might not always be available.
