### ISSUE TITLE
Wrong bic for bank code 20040000

### ISSUE THREAD

**Issue by anjaHirschmueller** [mdomke/schwifty#18]
The bic has to be COBADEFFXXX

**Comment by mdomke** [comment]
I don't think that that's correct. The bank code `200 400 00` relates to the Commerzbank Hamburg and some other branches (Bad Oldesloe, Ahrensburg, etc.) which have the BIC COBADE**HH**XXX. The same holds true for the bank code `200 400 05` which also designates a Commerzbank branch in Hamburg. Nevertheless there are other branches in Hamburg which relate to the BIC COBADE**FF**XXX (e.g. bank-code `200 400 20`). Have a look at this document [1] from the Bundesbank for further information.

[1] https://www.bundesbank.de/resource/blob/602630/b68d6f72d67826c37806f62a34e07a48/mL/blz-aktuell-xls-data.xlsx
