### ISSUE TITLE
Add bank registry for Montenegro

### ISSUE THREAD

**Issue by Djuka** [mdomke/schwifty#185]
Data is in attached JSON. Taken from Central bank of Montenegro webiste:
https://www.cbcg.me/me/kljucne-funkcije/platni-promet/platni-sistem/rtgs-sistem

[me.json](https://github.com/mdomke/schwifty/files/13993735/me.json)

**Comment by mdomke** [comment]
I'll add this to the next release. You could however also have created a pull-request to add the file as `schwifty/bank_registry/manual_me.json` 😉 . It's as simple as that!

**Comment by mdomke** [comment]
The bank registry for Montenegro is now part of the release `2024.04.0`
