### ISSUE TITLE
What is the meaning of "tbd" and "primary" properties in bank-registry.json?

### ISSUE THREAD

**Issue by osroca** [mdomke/schwifty#19]
Thanks for your work on this lib. 
I'm trying to enhance it with banks from Spain and I would like to know that are the meaning of properties `tbd` and `primary` listed tin the `bank-registry.json` file.

FYI, I'm trying to get official data from the Central Bank of Spain (Banco de España) and if they provide the banks data including the BIC/SWIFT code, I would like to include a script like `convert_blz_doc.py` to auto-populate the bank-registry file.

**Comment by mdomke** [comment]
I'm glad to hear that you can contribute bank code information for spain! Regarding your question:
* The `primary` fields denotes the primary branch for a group of branches that share the same bank code. I guess this is a specific thing for German banks. In Germany it might happen that there are several branches of the same bank that share the same bank code, in which case one of them is declared as the leading or primary branch. I would think that in your case you could just set the `primary` field always to `true`.
* The `tbd` field means "to be deleted". The field is derived from the German registry where bank codes can be scheduled to be deleted. In fact this field is not used anywhere in the code and I think I will remove it in a future version of Schwifty. I would suggest that you just don't add it to your data records.

**Comment by osroca** [comment]
Martin, thanks for your reply.
Just talked to the Central Bank of Spain and, unfortunately, they don't have available the SWFIT/BIC codes for the banks operating in Spain. The excuse it that those are provided by SWIFT, a private business.

Anyway, I'm trying to collect data from at least the most important banks in Spain and add it to the banks-registry.json. I'll set a PR once I have a few.

On the other hand, I was also thinking on changing a bit how schwifty reports the validation errors. ValueError is fine but it doesn't let you customize the error message, for internationalization for instance. Would you look fine if I set a PR implementing a custom Exception that wraps the ValueError, adding an error code that one could use to do these customizations? I would use codes like "length", "invalid_chars", ... I find these more simple to follow than numeric codes.

**Comment by mdomke** [comment]
Sorry to hear that you have to collect the data the hard way.

I would suggest to create custom exception classes that are derived from `ValueError` in order to express the current error situtation. E.g.
```python
class SchwiftyError(ValueError):
    pass


class InvalidCharacters(SchwiftyError):
    pass


class InvalidChecksum(SchwiftyError):
    pass


class InvalidFormat(SchwiftyError):
    pass


class InvalidLength(SchwiftyError):
    pass


class InvalidCountryCode(SchwiftyError):
    pass
```
In that way the API of the library would remain backwards compatible and we would still have dedicated exceptions for the different error situations. If necessary one could also think about having custom attributes on the exception classes if more information is required on the caller side.

**Comment by osroca** [comment]
Thanks for the suggestion, it makes total sense. I'll follow your advice.

Closing this issue for now.
