### ISSUE TITLE
Possible Error when validating Norwegian national bank accounts ending in zero.

### ISSUE THREAD

**Issue by PabloAJomer** [mdomke/schwifty#190]
I noticed that some national account numbers in Norway are possibly incorrectly deemed invalid. I am still investigating wether these accounts are actually valid ones but it seems there is a problem when the control digit is 0 for the National account number. For these cases the check_digit calculation below returns 11 which seems incorrect.

I would like some help with investigating this further where is the source for the algorithm that was used for the implementaion? I have found some information online that suggests that that it is indeed wrong.

If I'm correct I think a change like this would solve the problem.
```python
check_digit = 11 - (total % 11)
if check_digit == 11:
  check_digit = 0;
```

```python
def compute(self, components: list[str]) -> str:
        _, account_code = components
        value = account_code[2:] if account_code[:2] == "00" else "".join(components)

        weights = [5, 4, 3, 2, 7, 6, 5, 4, 3, 2]
        total: int = 0
        for n, c in zip(weights, value):
            total += n * int(c)

        check_digit = 11 - (total % 11)
        if check_digit == 10:
            raise InvalidAccountCode("Check digit does not compute: Invalid account code.")
        return str(check_digit % 10)
  ```

**Comment by Natim** [comment]
Hello @PabloAJomer thank you for reaching out, could you please provide us with a valid Norway IBAN that would validate this condition/edge case?

**Comment by PabloAJomer** [comment]
Yes here is an example which I think should be working but isn't. NO2660421439640

**Comment by PabloAJomer** [comment]
I am not entirely sure about it but I have debugged the code with the latest release of 2024.01.1.post0 and there the check_digit is calculated to 11. Which to me seems odd. When according to the algo specification I found it should be 0. If there is any link to the algorithm you implemented that would help me validate.

**Comment by Natim** [comment]
@PabloAJomer can you try this and tell us if it works? https://github.com/mdomke/schwifty/pull/191
I did a first attempt here but it's not exaclty what you've described.
Do you have a link to the official documentation about IBAN validation for Norway?

**Comment by PabloAJomer** [comment]
@Natim This works for me. A lot more elegant than my solution. I do not have the official documentation I have found a number of modulo 11 validators though with corresponding weights and those seem to validate this. I shall try and request an official source from our bank.

**Comment by Natim** [comment]
Ok I'll let @mdomke have a look at my PR then. I fixed the test.

**Comment by mdomke** [comment]
The spec for the national checksum algorithms is in most cases based on [this document](https://www.ecbs.org/Download/Tr201v3.9.pdf) and the implementation for Norway does indeed have an error. The pull-request from @Natim will provide a fix (thank you!).

**Comment by PabloAJomer** [comment]
Thanks @mdomke This is the document I used to check it but it seemed to be so old so I wasn't sure it was reliable.

**Comment by PabloAJomer** [comment]
When can I expect this to make it in to a release?

**Comment by mdomke** [comment]
I'm actually AFK until mid next week. I will craft a release end of next week the latest.
