### ISSUE TITLE
Are the iso3166 and pycountry dependencies doing the same thing?

### ISSUE THREAD

**Issue by sergei-maertens** [mdomke/schwifty#200]
Hi - thanks for this library! We're using it for IBAN validation.

While reviewing the dependencies pulled in by this library, I noticed that both iso3166 and pycountry are added. As far as I can tell, both libraries ship the alpha 2 and alpha 3 country codes and that appears to be how they are used in this library.

If this observation is correct, perhaps one of the dependencies could be dropped (probably drop the one that's used the least)? 

Of course, I might be missing something here, but if it could be an oversight, I can draw up a PR.

In case I'm plain wrong and there's a deliberate reason that I missed, I understand if you simply close this question :)

**Comment by mdomke** [comment]
Hej @sergei-maertens,
you are completely right. I will remove the `iso3166`-library from the dependencies. Thanks for the heads-up.

**Comment by mdomke** [comment]
The `iso3166`-dependency has been removed in release `2024.05.0`

**Comment by sergei-maertens** [comment]
Awesome, thanks for the quick follow up!
