### ISSUE TITLE
Missing BICs for Portuguese banks

### ISSUE THREAD

**Issue by tiagoafseixas** [mdomke/schwifty#202]
Hi,

We have been using your lib to determine the SWIFT (BIC) code from IBANs, and we found that the following are missing:

Code    Name                            SWIFT
0033	BANCO COMERCIAL PORTUGUÊS, SA   BCOMPTPL
0018	BANCO SANTANDER TOTTA, S.A.     TOTAPTPL

We are not sure if more are missing, but you can get a complete list here: https://www.santander.pt/pdfs/pdfs-empresas/netbanco-empresas-ajuda-online/netbanco-empresas-ajuda-online-documentos/sepa/Enderecos_SWIFT_Bancos_portugueses.pdf

Is it possible to add these to your lbirary? We are currently hardcodingg the SWIFT codes for these banks.

**Comment by mdomke** [comment]
Hi @tiagoafseixas,

would it be possible for you to create a pull-request where you add the missing bank entries to the [manual_pt.json](https://github.com/mdomke/schwifty/blob/main/schwifty/bank_registry/manual_pt.json)? I think I will currently not find the time to write a script that parses the PDF file you linked. Your help would be greatly appreciated.

**Comment by tiagoafseixas** [comment]
Will do. I was checking previous pull requests and it seems as if you created branches for other issues. Do you want to do the same here?

**Comment by mdomke** [comment]
I'm not sure if I understand what you mean by that. Just create a regular pull-request by forking this repo and applying the changes on a branch on your fork.
