### ISSUE TITLE
Missing declaration of dropping Python 3.8 support

### ISSUE THREAD

**Issue by bwoodsend** [mdomke/schwifty#220]
schwifty 2024.8.1 [uses](https://github.com/mdomke/schwifty/blob/3f4b34308356049fa15a4acf621c69e8f20a7ff6/schwifty/registry.py#L75) the Python 3.9 only `{} | {}` dict merge syntax but is still describing itself as [>=3.8 compatible](https://github.com/mdomke/schwifty/blob/3f4b34308356049fa15a4acf621c69e8f20a7ff6/pyproject.toml#L24) giving a:

```
unsupported operand type(s) for |: 'dict' and 'dict'
```
Either that syntax needs replacing or the minimium supported Python version should be bumped so that running a unpinned `pip install schwifty` with Python 3.8 doesn't lead to a broken installation (although you will need to yank the current release to meaningfully apply that fix).

**Comment by kirilsivenkovs** [comment]
Ran into the same issue, discovered schwifty is broken on 2024.8.0 as well - latest version that works on 3.8 is 2024.6.1.

Is it possible to perhaps fix the library for Python 3.8? It still has a few months left until EOL and the vast majority of Python libraries still support it.
