### ISSUE TITLE
Correct BIC but wrong bank name is returned

### ISSUE THREAD

**Issue by n49o7** [mdomke/schwifty#225]
In the case below, the correct bank_code, branch_code and BIC are returned. However, the bank_name seems wrong.

![image](https://github.com/user-attachments/assets/411eb7e8-954b-4b05-8333-7ff6eeb6867e)

A quick web search shows that this BIC is for Société Générale in France.

I wonder if this issue could be related: https://github.com/mdomke/schwifty/issues/91

**Comment by n49o7** [comment]
This issue is due to this name being given in `bank_registry/manual_fr.json` at [Line 2302](https://github.com/mdomke/schwifty/blob/44ae8e7629b98a16296b0827ba64b9326dadf25f/schwifty/bank_registry/manual_fr.json#L2302).

Should the file be updated, then?

**Comment by Natim** [comment]
Let's update the file if it is wrong indeed.

**Comment by n49o7** [comment]
_Inter Europe Conseil SAS_ is closed since 2019, though.
