### ISSUE TITLE
Incorrect national checksum after making exe with pyinstaller

### ISSUE THREAD

**Issue by Nidav07** [mdomke/schwifty#228]
Hello,
I have weird issue and maybe someone will be able to help me with it. I'm writing rather simple app and need to generate Polish IBANs. The app is done and when I'm debugging it everything works perfectly. However when I make .exe file with pyinstaller the IBANs are not generated correctly as national checksum is incorrect - I checked it return of compute_national_checksum is None for the .exe file - when debugging everything is correct. There is no message about it, simply it return None and generates incorrect IBANs - during debugging everything works fine. I have the latest versions of both schwifty and pyinstaller. To be honest I have no idea what can be done about it or where the problem is. I would really appreciate any help.

**Comment by Natim** [comment]
@Nidav07 how did you solve it in the end?

**Comment by Nidav07** [comment]
I didn't find reason behind it but in Polish bank accounts usually there already is national check sum so I modified some functions in the library to not calculate it but simply take it as input. With that everything works great.
