### ISSUE TITLE
UnicodeDecodeError when importing library in python3

### ISSUE THREAD

**Issue by MaikSoriano** [mdomke/schwifty#28]
Hi,
When I try to import the library in python3 it just break in an exception

`>>> from schwifty import IBAN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/schwifty/__init__.py", line 3, in <module>
    from schwifty.bic import BIC
  File "/usr/local/lib/python3.5/dist-packages/schwifty/bic.py", line 233, in <module>
    registry.build_index("bank", "bic", key="bic", accumulate=True)
  File "/usr/local/lib/python3.5/dist-packages/schwifty/registry.py", line 48, in build_index
    base = get(base_name)
  File "/usr/local/lib/python3.5/dist-packages/schwifty/registry.py", line 24, in get
    chunk = json.load(fp)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)
`

### Steps:
- Create new docker container with image ubuntu:16.04
- Enter in the container
- apt update
- apt install python3-pip
- pip3 install schwifty
- python3
- from schwifty import IBAN

### workaround:
- pip3 install schwifty==2020.1.1

**Comment by ZupitDevs** [comment]
Same issue, too using docker, but with Python 3.8.

Using schwifty==2020.5.3 

The docker image is based on the official python docker images: python:3.8.2-buster

```
from schwifty import IBAN
File "/usr/local/lib/python3.8/site-packages/schwifty/__init__.py", line 3, in <module>
from schwifty.bic import BIC
  File "/usr/local/lib/python3.8/site-packages/schwifty/bic.py", line 239, in <module>
    registry.build_index("bank", "bic", key="bic", accumulate=True)
  File "/usr/local/lib/python3.8/site-packages/schwifty/registry.py", line 49, in build_index
    base = get(base_name)
  File "/usr/local/lib/python3.8/site-packages/schwifty/registry.py", line 25, in get
    chunk = json.load(fp)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)
```

**Comment by mdomke** [comment]
@ZupitDevs I cannot reproduce this by running
```
λ docker run --rm -it python:3.8 bash -c 'pip install schwifty && python -c "from schwifty import IBAN; print(IBAN(\"DE75512108001245126199\"))"'
Collecting schwifty
  Downloading schwifty-2020.5.3-py2.py3-none-any.whl (177 kB)
     |████████████████████████████████| 177 kB 1.8 MB/s
Collecting iso3166>=0.7
  Downloading iso3166-1.0.1-py2.py3-none-any.whl (8.2 kB)
Collecting pycountry
  Downloading pycountry-19.8.18.tar.gz (10.0 MB)
     |████████████████████████████████| 10.0 MB 9.0 MB/s
Building wheels for collected packages: pycountry
  Building wheel for pycountry (setup.py) ... done
  Created wheel for pycountry: filename=pycountry-19.8.18-py2.py3-none-any.whl size=10627361 sha256=d977e43346e97adee33e7e9f8b6df0eb561e709f7623aefb2ea5a814175ad629
  Stored in directory: /root/.cache/pip/wheels/30/63/8c/165da7379ab28a48fdc297d0bb1823bbe06b06405566db3204
Successfully built pycountry
Installing collected packages: iso3166, pycountry, schwifty
Successfully installed iso3166-1.0.1 pycountry-19.8.18 schwifty-2020.5.3
DE75512108001245126199
```
and @MaikSoriano also
```
λ docker run --rm -it python:3.5 bash -c 'pip install schwifty && python -c "from schwifty import IBAN; print(IBAN(\"DE75512108001245126199\"))"'
```
seems to work just fine…
I can however reproduce the problem with your vanilla Ubuntu 16.04 installation. I think you'll have to adjust the locale in your container to support UTF-8. See [here](http://jaredmarkell.com/docker-and-locales/) for more information.

**Comment by ZupitDevs** [comment]
We use it in a Django project and the exception is thrown when Django bootstraps the project, since the file that has the schwifty import is read at that moment.

I've tried 
```
docker run --rm -it python:3.8.2-buster bash -c 'pip install schwifty && python -c "from schwifty import IBAN; print(IBAN(\"DE75512108001245126199\"))"'
```
which is  the same as you did but with the docker image we use, and I can't reproduce it  either.

Maybe it's some locale settings of the azure docker host machine (we were able to reproduce the bug on a dockerized  django app deployed on azure as docker web service)

**Comment by SuperMasterBlasterLaser** [comment]
I have a same issue in my Ubuntu Server 18 where python 3.6 is being used

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)

**Comment by SuperMasterBlasterLaser** [comment]
I think problem is being caused by parsing JSON file

     File "/home/dev/envs/project/lib/python3.6/encodings/ascii.py", line 26, in decode
[78.140.223.163] out:     return codecs.ascii_decode(input, self.errors)[0]

**Comment by mdomke** [comment]
@SuperMasterBlasterLaser Did you configure the locale of your system correctly as pointed out in the comment above?

**Comment by SuperMasterBlasterLaser** [comment]
@mdomke  No I just gave up and found another IBAN validator

**Comment by mdomke** [comment]
@SuperMasterBlasterLaser sorry to hear that it didn't work out for you. Out of interest: Which library did you end up using instead?

**Comment by manikos** [comment]
Same issue here using python3.6, ubuntu server 18. `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position`

**Comment by SuperMasterBlasterLaser** [comment]
> @SuperMasterBlasterLaser sorry to hear that it didn't work out for you. Out of interest: Which library did you end up using instead?

I have used this gist with changes https://gist.github.com/mperlet/f912b1e57d058bd1b07d78ed13de1f23

**Comment by manikos** [comment]
I have managed to fixed this error by changing locale on the remote machine Ubuntu 18. All I did was `sudo vim /etc/default/locale` and fill this file with:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

Then, I `. /etc/default/locale` and error gone. I don't know if this is the right way, but for now it works :)

**Comment by mdomke** [comment]
As pointed out before this issue occurs if the locales are not set correctly and is not a problem that can be solved by the library itself.

**Comment by jacopsd** [comment]
What do you mean by "locales are not set correctly"? What is correct or not correct? This lib should work with any locale, right? Thank you.

**Comment by jacopsd** [comment]
OK, setting environment variables LANG and LC_LANG to en_US.UTF-8 solved it
