### ISSUE TITLE
Does not work for country code SE

### ISSUE THREAD

**Issue by Jokezor** [mdomke/schwifty#36]
When trying to work with Swedish bank accounts I get the error:
ValueError: Bank code exceeds maximum size 3

I used the bank details:
    country_code = 'SE'
    bank_code = '6789'
    account_code = '123456789'

According to other calculators it should work.

**Comment by mdomke** [comment]
Hi @Jokezor,
thank you for reporting this issue! According to the official [IBAN registry](https://www.swift.com/sites/default/files/files/IBAN_Registry.pdf) from SWIFT then bank identifier for Swedish banks has a length of exactly 3 numeric characters. Is that wrong? `schwifty` uses the official registry as basis for the validation and we would need patch the parsed specification if there is an error. Please let me know about your findings!

**Comment by Jokezor** [comment]
I see! I will investigate it a bit.
We use bank_code combined with account_code to make payments and it's usually always 4 letters for the bank_code.

I will look into it and see if there is some reasoning behind the discrepancy.

**Comment by zydeco** [comment]
The 4 digit code (or 5 in some banks) is the clearing number, which should be prepended to the account code.
The bank code is 3 digits, you can find a table on [iban.se](https://www.iban.se) or [here](https://www.swedishbankers.se/media/1255/bank_id_iban_bic.pdf).

In your example, clearing number 6789 would belong to Handelsbanken, which has bank code 600.

country_code = 'SE'
bank_code = '600'
account_code = '6789123456789'

**Comment by jmfederico** [comment]
@Jokezor checkout #52 

Also, clearning number is not always included in the IBAN for Sweden, see https://www.swedishbankers.se/fraagor-vi-arbetar-med/betalningar/ny-nordisk-betalningsinfrastruktur/iban-och-svenskt-nationellt-kontonummer/

**Comment by jmfederico** [comment]
And to clarify, the bank_code in Sweden corresponds to the first 3 digits of the Main clearing number for each bank.
