### ISSUE TITLE
Custom exception types

### ISSUE THREAD

**Issue by eviltnan** [mdomke/schwifty#41]
ValueError with a string message is raised everywhere in the code, which makes it harder to identify which error has actually happened in the client code.
Like in:

```
        if len(bank_code) > bank_code_length:
            raise ValueError("Bank code exceeds maximum size {}".format(bank_code_length))

```

would improve to

```
        if len(bank_code) > bank_code_length:
            raise BankCodeTooLongError("Bank code exceeds maximum size {}".format(bank_code_length))
```

Please let me know if I can help.

BTW the lib is amazing, thank you for the outstanding job!

**Comment by mdomke** [comment]
Fixed by #44
