### ISSUE TITLE
Frozen app with pyinstaller  failes with schwifty

### ISSUE THREAD

**Issue by zdenop** [mdomke/schwifty#43]
I created [issue at pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/5390) where is also description how to reproduce the problem. As part of solution there is suggestion for schwifty:

> Alternatively, you could modify schwifty\registry.py to use regular os functions (listdir, etc.) instead of resource_listdir and resource_filename.

**Comment by mdomke** [comment]
I don't think that I will do something in that regard, especially since this problem is going to be fixed in an upcoming release of `pyinstaller` (after [this pull-request](https://github.com/pyinstaller/pyinstaller/pull/5284) is merged).

**Comment by christianferber** [comment]
Just checked with pyinstaller 6.5 and the issue is still there.
