### ISSUE TITLE
iban.bic = None for 'LT...' iban 

### ISSUE THREAD

**Issue by FakieKickflip** [mdomke/schwifty#46]
```
from schwifty import IBAN  

iban_obj = IBAN('LT663250028366006186')
> <IBAN=LT663250028366006186>

iban_obj.bic
> None
```

why does it have no bic?

**Comment by ckoehn** [comment]
Because it relies on the included bank registry which doesn't have a mapping from bank code to BIC for `LT` (See [documentation](https://schwifty.readthedocs.io/en/latest/api.html#schwifty.IBAN.bic)). Feel free to create a pull request to add it.

**Comment by adler-marmol** [comment]
> Because it relies on the included bank registry which doesn't have a mapping from bank code to BIC for `LT` (See [documentation](https://schwifty.readthedocs.io/en/latest/api.html#schwifty.IBAN.bic)). Feel free to create a pull request to add it.


Could you please give me contributor rights? I would like to add the `manual_lt.json` for LT bank's registry (verified on my own Revolut Account) , and include the new Revolut BIC as follow:
```
{
        "country_code": "LT",
        "bic": "REVOLT21",
        "bank_code": "32500",
        "name": "REVOLUT LTD",
        "short_name": "REVOLUT LTD",
        "primary": true
    }
```
![revolut](https://user-images.githubusercontent.com/83251937/116161298-cc502400-a6f3-11eb-8599-d0ce9116ab9d.jpg)

**Comment by mdomke** [comment]
You're free to open a pull request so that I can integrate your changes in the next release. In detail, you have to 
1. [Fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) the project 
2. Add a commit with your changes
3. Create a [pull request](https://help.github.com/en/articles/about-pull-requests) through the web UI

**Comment by mdomke** [comment]
I added some curated BICs for Lithuania to the release 2021.05.0
