### ISSUE TITLE
Using package_resources, which is not always part of a python runtime

### ISSUE THREAD

**Issue by a-recknagel** [mdomke/schwifty#57]
package_resources is part of setuptools, which is not necessarily part of a python distribution. I can write a PR which replaces it with importlib.metadata, which is part of the stdlib in 3.8+ and needs to be installed for <=3.7

**Comment by mdomke** [comment]
I don't know… Is it really worth it? You have to add conditional imports
```python
try:
    from importlib.resources import files
except:
    from importlib_resource import files
```
and conditional installs 
```
install_requires =
  importlib_resources;python_version=='3.7'
  importlib_metadata;python_version=='3.7'

```
and then the [files](https://docs.python.org/3.9/library/importlib.html#importlib.resources.files) function to traverse the contents of a package is only available in Python 3.9… If you have a convincing implementation, I'm really open to include it, but I myself am not very motivated to find a solution with `importlib` that works with all supported Python versions.
Thank you however for making me aware of the new functionality in `importlib`, which I didn't know about!
