### ISSUE TITLE
Is there a way to get the bank name from the bank code or IBAN or BIC?

### ISSUE THREAD

**Issue by bolinocroustibat** [mdomke/schwifty#63]
I know the question is a bit out of scope, but is there a way to get the bank name from the IBAN, BIC or bank code?

I see schwifty nicely gets the bank code, but couldn't find an API or module to get the bank name.

**Comment by mdomke** [comment]
```python
>>> from schwifty import BIC
>>> bic = BIC("GENODEM1GLS")
>>> bic.bank_name
'GLS Gemeinschaftsbank'
```
or
```python
>>> from schwifty import IBAN
>>> iban = IBAN("DE90100400000123456789")
>>> iban.bic.bank_name
'Commerzbank, Filiale Berlin 1'
```

**Comment by bolinocroustibat** [comment]
Wonderful, thanks. Missed that in the documentation, sorry!
