### ISSUE TITLE
France BBAN : multiple errors in registry + no BBAN checksum algorithm

### ISSUE THREAD

**Issue by sholan** [mdomke/schwifty#65]
Hello, working with french IBAN, I noticed schwifty doesn't pack an algorithm for BBAN checksum computing.

I just managed to make it work, but not being a developper and not having enough time, I certainly managed things the wrong way.

I've pushed my changes to my fork : [sholan/schwifty](https://github.com/sholan/schwifty) commit sha : 1816a01b008d062528be9effb02b62b26a6f7fce

Those changes are : 
- Adding : checksum/france.py with a sub-optimal code architecture but functionnal see [clef rib on wikipedia](https://fr.wikipedia.org/wiki/Cl%C3%A9_RIB#Algorithme_de_calcul_de_la_cl%C3%A9_RIB) to understand the key computing method (simplified)
- change : checksum/__init__.py to load the algorithm
- change : iban.py to add 'FR' in the if/elif list of country codes for which BBAN checksum is available
- change : iban_registry/generated.json : correction on account_code and branch_code positions (those informations are available in BANKDIRECTORYPLUS as published by swift)

I am sorry to not provide more help, as a simple pull request with everything perfectly done

**Comment by mdomke** [comment]
Hey @sholan, would you mind creating a pull request so that it is easier to review your changes?

**Comment by mdomke** [comment]
This was fixed in release [2022.03.1](https://github.com/mdomke/schwifty/releases/tag/2022.03.1)
