### ISSUE TITLE
N26 Bic missing

### ISSUE THREAD

**Issue by brunovila** [mdomke/schwifty#66]
I have found an new bank that the BIC is not generated
The IBAN starts with ES38 1563, and the bank is **N26 Bank Gmbh, Sucursal En Espana**

Probably all the Neobanks are not included (N26, Revolut, Rebellion, ....)

**Comment by mdomke** [comment]
The banks are currently read from [here](https://www.iban.es/bancos-extranjeros/) and N26 is missing there, but we can add a manual overwrite for the missing banks by adding them to `schwifty/bank_registry/manual_es.json`.

**Comment by mdomke** [comment]
This was fixed in release [2022.02.0](https://github.com/mdomke/schwifty/releases/tag/)
