### ISSUE TITLE
Faulty data in generated_nl.json

### ISSUE THREAD

**Issue by TheoSinnige** [mdomke/schwifty#77]
The source file for Dutch banks currently has a blank line on line 78. This resulted in a faulty entry in [generated_nl.json](https://github.com/mdomke/schwifty/blob/master/schwifty/bank_registry/generated_nl.json#L587-L592):
```json
  {
    "country_code": "NL",
    "primary": true,
    "bic": "",
    "bank_code": "",
    "name": "",
    "short_name": ""
  },
```

I created #73 and #74 for this assuming that `generated_nl.json` would be regenerated at some point. But more than a month later the faulty entry is still there. Do I need to submit a pull request for removing the entry itself as well?

**Comment by mdomke** [comment]
@TheoSinnige the bank registry has been regenerated in the meantime, but your pull-request didn't fix the problem (which I also didn't realize while reviewing it). Nevertheless, I created a new release now `2022.04.0` where the bogus line is removed from the dutch bank registry.
